### ISSUE TITLE
about:blank tab opens up in addition to pop-up for the social share

### ISSUE THREAD

**Issue by mzhukovs** [thisDOTname/vue-share-it#7]
Hi there - great library.

One issue (tested in both Edge and Chrome) is that when user clicks one of the share links, in addition to the expected pop-up for the social site, an empty "about:blank" tab also opens up. Is there a way around this?

Using this in a gridsome project.

Thanks

**Comment by thisDOTname** [comment]
Hi @mzhukovs, thanks for identifying the issue. It has now been fixed in v1.1.3
